# Generated by Django 6.0.4 on 2026-04-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("doctor", "Doctor"),
                    ("staff", "Staff"),
                    ("ops", "Operations"),
                ],
                db_index=True,
                default="staff",
                max_length=20,
            ),
        ),
    ]
