# Generated by Django 6.0.4 on 2026-04-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mappings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientdoctormapping",
            name="slot_end",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="patientdoctormapping",
            name="slot_start",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
